version: "3"

services:

  alt_django_server:
    build:
      context: .
      dockerfile: ServerDockerfile
    container_name: alt_django_server
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DOCKER=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    networks:
      - default
    restart: unless-stopped

#  fastapi_server:
#    build:
#      context: .
#      dockerfile: ServerDockerfile
#    container_name: fastapi_server
#    command: uvicorn ws:app --reload --host 0.0.0.0 --port 8001
#    environment:
#      - DOCKER=1
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    ports:
#      - "8001:8001"
#      - "9090:9090"
#      - "1919:1919"
#    networks:
#      - default
#    volumes:
#      - ./db.sqlite3:/app/db.sqlite3
#    restart: unless-stopped